import fs from "fs";

const ideas = JSON.parse(fs.readFileSync("./ideas.json"));

if (!fs.existsSync("./apps")) {
  fs.mkdirSync("./apps");
}

ideas.forEach((idea) => {

  const id = Date.now() + "_" + Math.floor(Math.random()*10000);
  const folder = `./apps/app_${id}`;

  fs.mkdirSync(folder);

  const html = `
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>${idea}</title>
<style>
body{
font-family:Arial;
max-width:800px;
margin:40px auto;
}
button{
padding:10px 20px;
font-size:16px;
}
</style>
</head>
<body>

<h1>${idea}</h1>

<p>This tool was generated by AI_FABRIK.</p>

<button onclick="alert('Tool coming soon')">
Run tool
</button>

</body>
</html>
`;

  fs.writeFileSync(folder + "/index.html", html);

});

console.log("apps created");