/**
 * REVENUE COLLECTOR – Track real revenue generated by factory products.
 *
 * Reads from monetization/stripe and monetization/ads configs; simulates revenue
 * when no real signals exist. Structure allows real APIs to replace simulation later.
 * Writes metrics/{slug}.json and metrics/factory_revenue.json.
 * Never throws; all errors caught and logged.
 */

import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = process.cwd();
const MONETIZATION_ROOT = path.join(root, "monetization");
const STRIPE_DIR = path.join(MONETIZATION_ROOT, "stripe");
const ADS_DIR = path.join(MONETIZATION_ROOT, "ads");
const METRICS_DIR = path.join(root, "metrics");
const FACTORY_REVENUE_PATH = path.join(METRICS_DIR, "factory_revenue.json");
const LOG_PATH = path.join(root, "logs", "revenue_collector.log");

async function revenueLog(level, message, data = null) {
  const ts = new Date().toISOString();
  const payload = data != null && data !== undefined
    ? { level, message, ...(typeof data === "object" ? data : { value: data }) }
    : { level, message };
  const extra = typeof payload === "object" && payload.message
    ? Object.fromEntries(Object.entries(payload).filter(([k]) => k !== "message"))
    : {};
  const line = ts + " [" + (level || "info").toUpperCase() + "] " + (payload.message || message) + (Object.keys(extra).length ? " " + JSON.stringify(extra) : "");
  try {
    await fs.mkdir(path.dirname(LOG_PATH), { recursive: true });
    await fs.appendFile(LOG_PATH, line + "\n", "utf-8");
  } catch {
    // ignore
  }
}

/**
 * Data source: read revenue signals from provider configs.
 * Replace this with real API calls (Stripe API, AdSense API) when keys are available.
 * @returns {{ revenue_today: number, revenue_month: number, transactions: number }}
 */
async function readRevenueFromProviders(slug, paymentProvider) {
  let revenueToday = 0;
  let revenueMonth = 0;
  let transactions = 0;

  const stripePath = path.join(STRIPE_DIR, slug + ".json");
  const adsPath = path.join(ADS_DIR, slug + ".json");

  try {
    if (paymentProvider === "stripe" || !paymentProvider) {
      const raw = await fs.readFile(stripePath, "utf-8").catch(() => null);
      if (raw) {
        const config = JSON.parse(raw);
        if (config.revenue_today != null) revenueToday = Number(config.revenue_today) || 0;
        if (config.revenue_month != null) revenueMonth = Number(config.revenue_month) || 0;
        if (config.transactions != null) transactions = Number(config.transactions) || 0;
      }
    }
    if (paymentProvider === "google_adsense" || paymentProvider === "ads" || (!paymentProvider && revenueToday === 0 && revenueMonth === 0)) {
      const raw = await fs.readFile(adsPath, "utf-8").catch(() => null);
      if (raw) {
        const config = JSON.parse(raw);
        if (config.revenue_today != null) revenueToday = Number(config.revenue_today) || 0;
        if (config.revenue_month != null) revenueMonth = Number(config.revenue_month) || 0;
        if (config.transactions != null) transactions = Number(config.transactions) || 0;
      }
    }
  } catch {
    // ignore read errors
  }

  // Simulate when no revenue fields present (placeholders only)
  if (revenueToday === 0 && revenueMonth === 0 && transactions === 0) {
    revenueToday = 0;
    revenueMonth = 0;
    transactions = 0;
  }

  return { revenue_today: revenueToday, revenue_month: revenueMonth, transactions };
}

/**
 * Refresh factory_revenue.json from all product metrics in metrics/.
 */
async function updateFactoryRevenue() {
  try {
    await fs.mkdir(METRICS_DIR, { recursive: true });
    const entries = await fs.readdir(METRICS_DIR, { withFileTypes: true }).catch(() => []);
    const files = entries.filter((e) => e.isFile() && e.name.endsWith(".json") && e.name !== "factory_revenue.json");

    let totalRevenueToday = 0;
    let totalRevenueMonth = 0;

    for (const f of files) {
      try {
        const raw = await fs.readFile(path.join(METRICS_DIR, f.name), "utf-8");
        const data = JSON.parse(raw);
        totalRevenueToday += Number(data.revenue_today) || 0;
        totalRevenueMonth += Number(data.revenue_month) || 0;
      } catch {
        // skip invalid files
      }
    }

    const factoryRevenue = {
      total_products: files.length,
      total_revenue_today: totalRevenueToday,
      total_revenue_month: totalRevenueMonth,
      last_updated: new Date().toISOString()
    };
    await fs.writeFile(FACTORY_REVENUE_PATH, JSON.stringify(factoryRevenue, null, 2), "utf-8");
  } catch (e) {
    await revenueLog("error", "updateFactoryRevenue failed", { error: e.message });
  }
}

/**
 * Collect revenue metrics for a product and persist. Updates factory summary.
 *
 * @param {Object} product - { name, slug?, pricing_model?, payment_provider? }
 * @returns {Promise<{ product_name, slug, revenue_today, revenue_month, transactions, last_updated }>}
 */
export async function collectRevenueMetrics(product) {
  const now = new Date().toISOString();
  const defaultResult = {
    product_name: "",
    slug: "",
    revenue_today: 0,
    revenue_month: 0,
    transactions: 0,
    last_updated: now
  };

  if (!product || typeof product !== "object") {
    await revenueLog("warn", "collectRevenueMetrics called with invalid product", {});
    return defaultResult;
  }

  const name = product.name || "Product";
  const slug = (product.slug || name).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "product";
  const paymentProvider = product.payment_provider || null;

  try {
    const { revenue_today, revenue_month, transactions } = await readRevenueFromProviders(slug, paymentProvider);

    const metrics = {
      product_name: name,
      slug,
      revenue_today: revenue_today,
      revenue_month: revenue_month,
      transactions: transactions,
      last_updated: now
    };

    await fs.mkdir(METRICS_DIR, { recursive: true });
    await fs.writeFile(path.join(METRICS_DIR, slug + ".json"), JSON.stringify(metrics, null, 2), "utf-8");

    await updateFactoryRevenue();

    await revenueLog("info", "Revenue metrics updated", { product: slug });
    return metrics;
  } catch (e) {
    await revenueLog("error", "collectRevenueMetrics failed", { slug, error: e.message });
    return { ...defaultResult, product_name: name, slug };
  }
}
