/**
 * RELEASE MANAGER – Factory versioning and release metadata.
 *
 * Reads: factory_monitor/factory_health.json, maintenance_system/cleanup_report.json,
 * logs/system_repairs.json, factory_release/factory_version.json
 *
 * If factory is stable (pipeline_success_rate >= 0.90, no critical chaos failures, apps > 0):
 *   bumps version (minor), writes factory_version.json and release_notes.md.
 *
 * Only generates release metadata; never interrupts the pipeline.
 */

import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = process.cwd();
const RELEASE_DIR = path.join(root, "factory_release");
const VERSION_FILE = path.join(RELEASE_DIR, "factory_version.json");
const RELEASE_NOTES_FILE = path.join(RELEASE_DIR, "release_notes.md");
const HEALTH_FILE = path.join(root, "factory_monitor", "factory_health.json");
const CLEANUP_REPORT_FILE = path.join(root, "maintenance_system", "cleanup_report.json");
const REPAIRS_LOG_FILE = path.join(root, "logs", "system_repairs.json");

const MIN_PIPELINE_SUCCESS_RATE = 0.9;
const MAX_CHAOS_FAILURES_24H = 0;

async function readJson(filePath, defaultValue = null) {
  try {
    const raw = await fs.readFile(filePath, "utf-8");
    return JSON.parse(raw);
  } catch {
    return defaultValue;
  }
}

function parseSemver(version) {
  const match = String(version || "0.0.0").match(/^(\d+)\.(\d+)\.(\d+)/);
  if (!match) return { major: 0, minor: 0, patch: 0 };
  return {
    major: parseInt(match[1], 10),
    minor: parseInt(match[2], 10),
    patch: parseInt(match[3], 10)
  };
}

function bumpMinor(version) {
  const { major, minor } = parseSemver(version);
  return `${major}.${minor + 1}.0`;
}

/**
 * Determine if factory is stable from health.
 */
function isStable(health) {
  if (!health) return false;
  const apps = health.apps || {};
  const system = health.system || {};
  const totalApps = Number(apps.total) || 0;
  const pipelineRate = Number(system.pipeline_success_rate);
  const chaosFailures = Number(system.chaos_failures_last_24h) || 0;

  return (
    totalApps > 0 &&
    pipelineRate >= MIN_PIPELINE_SUCCESS_RATE &&
    chaosFailures <= MAX_CHAOS_FAILURES_24H
  );
}

/**
 * Generate release notes content from health, cleanup report, repairs, previous version.
 */
function generateReleaseNotes(health, cleanupReport, repairs, prevVersion, newVersion, releasedAt) {
  const apps = health?.apps || {};
  const revenue = health?.revenue || {};
  const system = health?.system || {};
  const actions = cleanupReport?.actions || [];
  const repairList = Array.isArray(repairs) ? repairs : [];

  const lines = [
    `# AI_FABRIK Release ${newVersion}`,
    "",
    `**Released:** ${releasedAt}`,
    "",
    "## Summary",
    "",
    `- **Apps:** ${apps.total ?? 0} total (${apps.profitable ?? 0} profitable, ${apps.growing ?? 0} growing, ${apps.stagnant ?? 0} stagnant, ${apps.paused ?? 0} paused)`,
    `- **Revenue:** $${revenue.total ?? 0} (growth rate: ${(Number(revenue.growth_rate) * 100).toFixed(1)}%)`,
    `- **Pipeline success rate:** ${((system.pipeline_success_rate ?? 0) * 100).toFixed(1)}%`,
    `- **Build failures (24h):** ${system.build_failures ?? 0}`,
    `- **Repairs (24h):** ${system.repairs_last_24h ?? 0}`,
    `- **Chaos test failures (24h):** ${system.chaos_failures_last_24h ?? 0}`,
    "",
    "## System stability",
    "",
    `Status: **stable**. Pipeline success rate meets threshold (≥${MIN_PIPELINE_SUCCESS_RATE * 100}%), no critical chaos failures, apps > 0.`,
    "",
    "## Repairs applied",
    "",
    repairList.length === 0
      ? "No repairs recorded in this period."
      : `Total repairs in log: ${repairList.length}. Recent entries inform system recovery and integrity.`,
    "",
    "## Improvements since last release",
    ""
  ];

  if (actions.length === 0) {
    lines.push("- No cleanup actions in report.");
  } else {
    for (const a of actions) {
      const type = a.type || "action";
      const count = Array.isArray(a.files) ? a.files.length : 0;
      lines.push(`- **${type}:** ${count} file(s) affected.`);
    }
  }

  lines.push("");
  lines.push("---");
  lines.push(`*Previous version: ${prevVersion}. Auto-generated by release manager.*`);
  return lines.join("\n");
}

/**
 * Run release manager: check stability, optionally bump version and write release notes.
 * Only generates metadata; never interrupts pipeline.
 * @returns {Promise<{ ok: boolean, stable: boolean, version?: string, released?: boolean }>}
 */
export async function runReleaseManager() {
  const health = await readJson(HEALTH_FILE);
  const cleanupReport = await readJson(CLEANUP_REPORT_FILE);
  const repairsData = await readJson(REPAIRS_LOG_FILE, { repairs: [] });
  const repairs = Array.isArray(repairsData.repairs) ? repairsData.repairs : [];

  const stable = isStable(health);
  await fs.mkdir(RELEASE_DIR, { recursive: true });

  let current = await readJson(VERSION_FILE, { version: "5.0.0", released_at: null, status: "unreleased" });
  const prevVersion = current.version || "5.0.0";

  if (!stable) {
    const report = {
      version: prevVersion,
      released_at: current.released_at ?? null,
      status: "unstable",
      last_checked: new Date().toISOString(),
      reason: "Stability criteria not met (pipeline success rate, chaos failures, or apps count)."
    };
    await fs.writeFile(VERSION_FILE, JSON.stringify(report, null, 2), "utf-8");
    return { ok: true, stable: false, version: prevVersion, released: false };
  }

  const newVersion = bumpMinor(prevVersion);
  const releasedAt = new Date().toISOString();

  const versionPayload = {
    version: newVersion,
    released_at: releasedAt,
    status: "stable"
  };
  await fs.writeFile(VERSION_FILE, JSON.stringify(versionPayload, null, 2), "utf-8");

  const releaseNotes = generateReleaseNotes(health, cleanupReport, repairs, prevVersion, newVersion, releasedAt);
  await fs.writeFile(RELEASE_NOTES_FILE, releaseNotes, "utf-8");

  return { ok: true, stable: true, version: newVersion, released: true };
}
