/**
 * APP BUILDER – Bygger appar från ideas.json (batch).
 * Roll: Läser idéer, skapar app-mappar och deploy/index.html. Kör ej automatiskt i loop.
 */
import fs from "fs";
import path from "path";

const ideasPath = path.join(process.cwd(), "ideas", "ideas.json");
const ideas = JSON.parse(fs.readFileSync(ideasPath, "utf-8"));

const appsDir = path.join(process.cwd(), "apps");
const deployDir = path.join(process.cwd(), "deploy");

if (!fs.existsSync(appsDir)) {
  fs.mkdirSync(appsDir, { recursive: true });
}

const appFolders = [];

ideas.forEach((idea) => {
  const id = Date.now() + "_" + Math.floor(Math.random() * 10000);
  const folder = path.join(appsDir, `app_${id}`);
  fs.mkdirSync(folder, { recursive: true });

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${idea}</title>
<style>
body { font-family: Arial; max-width: 800px; margin: 40px auto; }
button { padding: 10px 20px; font-size: 16px; }
</style>
</head>
<body>
<h1>${idea}</h1>
<p>This tool was generated by AI_FABRIK.</p>
<button onclick="alert('Tool coming soon')">Run tool</button>
</body>
</html>
`;

  fs.writeFileSync(path.join(folder, "app.html"), html, "utf-8");
  appFolders.push({ name: idea, folder: path.relative(process.cwd(), folder).replace(/\\/g, "/") });
});

let indexHTML = `
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>AI FABRIK</title>
<style>
body { font-family: Arial; max-width: 800px; margin: 40px auto; }
a { display: block; margin: 10px 0; color: #1a73e8; text-decoration: none; }
a:hover { text-decoration: underline; }
</style>
</head>
<body>
<h1>AI FABRIK</h1>
<p>Automatiskt genererade micro-appar</p>
`;

appFolders.forEach((app) => {
  const relativePath = path.relative(deployDir, path.join(appsDir, path.basename(app.folder))).replace(/\\/g, "/") + "/app.html";
  indexHTML += `<a href="${relativePath}" target="_blank">${app.name}</a>\n`;
});

indexHTML += `
</body>
</html>
`;

if (!fs.existsSync(deployDir)) {
  fs.mkdirSync(deployDir, { recursive: true });
}
fs.writeFileSync(path.join(deployDir, "index.html"), indexHTML, "utf-8");

console.log("Apps skapade och deploy/index.html uppdaterad!");
