/**
 * UPDATE APPS RUN – Uppdaterar app.html i ./apps med enkel Run-knapp.
 * Roll: Enkel batch-uppdatering. Kör MANUELLT – ej i automatisk loop (risk för överskrivning).
 */
import fs from "fs";
import path from "path";

const appsDir = path.join(process.cwd(), "apps");

if (!fs.existsSync(appsDir)) {
  console.warn("apps directory not found");
  process.exit(1);
}

const folders = fs.readdirSync(appsDir).filter((f) => f.startsWith("app_"));

folders.forEach((folder) => {
  const filePath = path.join(appsDir, folder, "app.html");
  if (!fs.existsSync(filePath)) return;

  const ideaName = folder;
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${ideaName}</title>
<style>
body { font-family: Arial; max-width: 800px; margin: 40px auto; }
button { padding: 10px 20px; font-size: 16px; }
#output { margin-top: 20px; padding: 10px; border: 1px solid #ccc; }
</style>
</head>
<body>
<h1>${ideaName}</h1>
<p>This tool was generated by AI_FABRIK.</p>
<button id="runBtn">Run tool</button>
<div id="output"></div>

<script>
document.getElementById("runBtn").addEventListener("click", () => {
  const output = document.getElementById("output");
  output.innerHTML = "✅ Tool executed successfully!";
});
</script>

</body>
</html>
`;

  fs.writeFileSync(filePath, html, "utf-8");
});

console.log("Alla appar uppdaterade med fungerande Run-knapp!");
