/**
 * WORKERS – Bygger appar från godkända idéer utan OpenAI.
 *
 * Roll:
 * - Skapar app.html (själva verktyget)
 * - Skapar deploy/index.html per app (landing med enkel copy)
 * - Skriver enkel marketing.txt baserat på idén
 *
 * Allt är deterministiskt mall-baserat; ingen OpenAI används.
 */

import fs from "fs/promises";

function slugifyId() {
  return `app_${Date.now()}_${Math.floor(Math.random() * 10000)}`;
}

function createMarketingText(idea) {
  return [
    `Unlock the power of "${idea}".`,
    "",
    "- Designed for busy people and small teams.",
    "- Simple, fast and focused on one clear job.",
    "- Ready to fit into your existing workflow.",
    "",
    "Start experimenting with a lightweight MVP today."
  ].join("\n");
}

function createAppHtml(idea) {
  const safeTitle = idea || "AI_FABRIK App";
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${safeTitle}</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="min-h-screen bg-slate-950 text-slate-50 flex flex-col">
  <header class="border-b border-slate-800 bg-slate-950/80 backdrop-blur">
    <div class="max-w-5xl mx-auto px-4 py-4 flex items-center justify-between">
      <div class="flex items-center gap-2">
        <span class="inline-flex h-8 w-8 items-center justify-center rounded-lg bg-indigo-500 text-white font-bold">A</span>
        <div>
          <div class="text-sm font-semibold tracking-wide uppercase text-slate-300">AI_FABRIK</div>
          <div class="text-xs text-slate-500">Autogenerated tool</div>
        </div>
      </div>
      <a href="#" class="text-xs font-medium text-slate-400 hover:text-slate-100 transition">Powered by your AI-factory</a>
    </div>
  </header>

  <main class="flex-1">
    <section class="border-b border-slate-800 bg-gradient-to-b from-slate-950 via-slate-950 to-slate-900">
      <div class="max-w-5xl mx-auto px-4 py-10 md:py-14 grid md:grid-cols-[minmax(0,2fr)_minmax(0,1.5fr)] gap-10 items-center">
        <div>
          <p class="text-xs font-medium tracking-[0.22em] text-indigo-400 uppercase mb-3">Live concept</p>
          <h1 class="text-3xl md:text-4xl lg:text-5xl font-semibold tracking-tight text-slate-50 mb-4">${safeTitle}</h1>
          <p class="text-sm md:text-base text-slate-300 leading-relaxed mb-6">
            A lightweight, auto-generated SaaS-style tool from your AI_FABRIK.
            Use this as a starting point to explore the idea, capture workflows and validate if it deserves a full build.
          </p>
          <div class="flex flex-wrap items-center gap-3">
            <button
              id="runToolBtn"
              class="inline-flex items-center justify-center rounded-lg bg-indigo-500 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-400 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950 transition"
            >
              Run quick test
            </button>
            <button
              id="clearToolBtn"
              class="inline-flex items-center justify-center rounded-lg border border-slate-700 px-3.5 py-2 text-xs font-medium text-slate-200 hover:bg-slate-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-500 transition"
            >
              Clear results
            </button>
            <p class="text-[11px] text-slate-500">
              Uses only local browser storage. No backend, no external APIs.
            </p>
          </div>
        </div>
        <div class="border border-slate-800 rounded-xl bg-slate-950/60 shadow-lg shadow-black/40 overflow-hidden">
          <div class="px-4 py-3 border-b border-slate-800 flex items-center justify-between bg-slate-950/80">
            <span class="text-xs font-medium text-slate-300">Idea scratchpad</span>
            <span class="text-[10px] text-slate-500">Local only</span>
          </div>
          <div class="p-4 space-y-3">
            <label class="block text-[11px] font-medium text-slate-400 mb-1" for="noteInput">
              Write down flows, personas or test cases for this idea:
            </label>
            <textarea
              id="noteInput"
              class="w-full h-32 rounded-md border border-slate-800 bg-slate-950/70 px-2.5 py-2 text-xs text-slate-100 placeholder:text-slate-500 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-indigo-400"
              placeholder="Example: 'As a user I want to…'"
            ></textarea>
            <div class="text-[11px] text-slate-500">
              The text is stored in your browser only (localStorage) so you can iterate quickly without losing notes.
            </div>
            <div id="output" class="mt-2 text-[11px] text-slate-300 min-h-[1.5em]"></div>
          </div>
        </div>
      </div>
    </section>

    <section class="border-t border-slate-900 bg-slate-950">
      <div class="max-w-5xl mx-auto px-4 py-6 flex flex-wrap items-center justify-between gap-3">
        <p class="text-[11px] text-slate-500">
          This page is a deterministic template – feel free to edit the HTML to evolve the product further.
        </p>
        <div class="flex gap-2 text-[11px] text-slate-500">
          <span class="inline-flex items-center gap-1">
            <span class="h-1 w-1 rounded-full bg-emerald-400"></span>
            MVP ready
          </span>
          <span>•</span>
          <span>Generated by AI_FABRIK</span>
        </div>
      </div>
    </section>
  </main>

  <script>
    (function() {
      const noteKey = "ai_fabrik_note_${Date.now()}";
      const noteInput = document.getElementById("noteInput");
      const output = document.getElementById("output");
      const runBtn = document.getElementById("runToolBtn");
      const clearBtn = document.getElementById("clearToolBtn");

      if (noteInput && window.localStorage) {
        const saved = localStorage.getItem(noteKey);
        if (saved) {
          noteInput.value = saved;
        }
        noteInput.addEventListener("input", () => {
          localStorage.setItem(noteKey, noteInput.value || "");
        });
      }

      if (runBtn && output && noteInput) {
        runBtn.addEventListener("click", () => {
          const text = (noteInput.value || "").trim();
          if (!text) {
            output.textContent = "⚠️ Write something in the scratchpad first to run a quick test.";
            return;
          }
          const length = text.split(/\\s+/).filter(Boolean).length;
          output.textContent = "✅ Quick test complete – you captured ~" + length + " word(s). Keep iterating and refine the strongest use-cases.";
        });
      }

      if (clearBtn && output && noteInput && window.localStorage) {
        clearBtn.addEventListener("click", () => {
          noteInput.value = "";
          localStorage.removeItem(noteKey);
          output.textContent = "";
        });
      }
    })();
  </script>
</body>
</html>
`;
}

function createLandingPageHtml(idea, marketingText) {
  const safeTitle = idea || "AI_FABRIK Product";
  const safeMarketing = (marketingText || "").split("\n").map((l) => l.trim()).filter(Boolean);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${safeTitle} – Landing</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="min-h-screen bg-slate-950 text-slate-50 flex flex-col">
  <main class="flex-1">
    <section class="bg-gradient-to-b from-slate-950 via-slate-950 to-slate-900 border-b border-slate-800">
      <div class="max-w-4xl mx-auto px-4 py-10 space-y-6">
        <div class="inline-flex items-center gap-2 rounded-full border border-slate-800 bg-slate-950/80 px-3 py-1 text-[11px] text-slate-400">
          <span class="h-1.5 w-1.5 rounded-full bg-emerald-400"></span>
          <span>Concept generated in AI_FABRIK</span>
        </div>
        <h1 class="text-3xl md:text-4xl font-semibold tracking-tight text-slate-50">
          ${safeTitle}
        </h1>
        <div class="space-y-2 text-sm text-slate-300">
          ${safeMarketing.map((line) => `<p>${line}</p>`).join("\n")}
        </div>
        <div class="flex flex-wrap items-center gap-3 pt-2">
          <a
            href="./app.html"
            class="inline-flex items-center justify-center rounded-lg bg-indigo-500 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-400 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950 transition"
          >
            Open interactive prototype
          </a>
          <span class="text-[11px] text-slate-500">
            This is a static MVP landing; you can customize the HTML to move towards production.
          </span>
        </div>
      </div>
    </section>
  </main>
</body>
</html>
`;
}

async function createOneApp(idea) {
  const id = slugifyId();
  const appFolder = `apps/${id}`;
  const deployFolder = `deploy/${id}`;

  await fs.mkdir(appFolder, { recursive: true });
  await fs.mkdir(deployFolder, { recursive: true });

  const marketingText = createMarketingText(idea);
  const appHtml = createAppHtml(idea);
  const landingHtml = createLandingPageHtml(idea, marketingText);

  await fs.writeFile(`${appFolder}/idea.txt`, idea);
  await fs.writeFile(`${appFolder}/app.html`, appHtml);
  await fs.writeFile(`${appFolder}/marketing.txt`, marketingText);

  await fs.writeFile(`${deployFolder}/index.html`, landingHtml);
  await fs.writeFile(`${deployFolder}/app.html`, appHtml);

  console.log("APP CREATED (no-OpenAI workers):", id);
  return id;
}

export async function createApps(ideas) {
  if (!Array.isArray(ideas)) {
    ideas = String(ideas || "")
      .split("\n")
      .map((i) => i.replace(/^[0-9]+\.\s*/, "").trim())
      .filter(Boolean);
  }

  const createdIds = [];
  for (const idea of ideas) {
    const id = await createOneApp(idea);
    createdIds.push(id);
  }

  console.log("DONE BUILDING APPS (no-OpenAI workers)");
  return createdIds;
}

